// AnotherAtlCarServer.idl : IDL source for AnotherAtlCarServer.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (AnotherAtlCarServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(7FE41805-124B-44AE-BEAE-C3491E35372B),
		oleautomation,
		helpstring("IStartable Interface"),
		pointer_default(unique)
	]
	interface IStartable : IUnknown
	{
		HRESULT Start();
	};
	[
		object,
		uuid(B001A308-8D66-4d23-84A4-B67615646ABB),
		oleautomation,
		helpstring("IStoppable Interface"),
		pointer_default(unique)
	]
	interface IStoppable : IUnknown
	{
		HRESULT Break();
	};

[
	uuid(7B69AEB6-F0B7-46BB-8AD4-1CACD1EA5AE9),
	version(1.0),
	helpstring("AnotherAtlCarServer 1.0 Type Library")
]
library ANOTHERATLCARSERVERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(862C5338-8AD7-43A3-A9A7-F21B145D61D0),
		helpstring("CoTruck Class")
	]
	coclass CoTruck
	{
		[default] interface IStartable;
		interface IStoppable; 
	};
};
