//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3617.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("5.0.0.0")]
[assembly: System.Windows.Forms.AxHost.TypeLibraryTimeStamp("2/17/2002 2:54:26 PM")]

namespace AxSimpleVb6AxCtrl 
{   
	[System.Windows.Forms.AxHost.ClsidAttribute("{bfebb550-733e-42be-8be5-8e093d25984e}")]
	[System.ComponentModel.DesignTimeVisibleAttribute(true)]
	[System.ComponentModel.DefaultEvent("TextChangedEvent")]
	public class AxLameColorControl : System.Windows.Forms.AxHost 
	{
        
		private SimpleVb6AxCtrl._LameColorControl ocx;
        
		private AxLameColorControlEventMulticaster eventMulticaster;
        
		private System.Windows.Forms.AxHost.ConnectionPointCookie cookie;
        
		public AxLameColorControl() : 
			base("bfebb550-733e-42be-8be5-8e093d25984e") 
		{
		}
        
		[System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
		[System.Runtime.InteropServices.DispIdAttribute(1745027072)]
		[System.ComponentModel.Description("This sets the text which is to be displayed in the label."), 
		System.ComponentModel.Category("Lame Stuff")]
		public virtual string TheText 
		{
			get 
			{
				if ((this.ocx == null)) 
				{
					throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TheText", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
				}
				return this.ocx.TheText;
			}
			set 
			{
				if ((this.ocx == null)) 
				{
					throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TheText", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
				}
				this.ocx.TheText = value;
			}
		}
        
		[System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
		[System.Runtime.InteropServices.DispIdAttribute(-501)]
		[System.Runtime.InteropServices.ComAliasNameAttribute("System.UInt32")]
		[System.ComponentModel.Description("This lets you set the background color to any RGB value."), 
		System.ComponentModel.Category("Lame Stuff")]
		public virtual System.Drawing.Color BackGroundColor 
		{
			get 
			{
				if ((this.ocx == null)) 
				{
					throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("BackGroundColor", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
				}
				return GetColorFromOleColor(((System.UInt32)(this.ocx.BackGroundColor)));
			}
			set 
			{
				if ((this.ocx == null)) 
				{
					throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("BackGroundColor", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
				}
				this.ocx.BackGroundColor = ((System.UInt32)(GetOleColorFromColor(value)));
			}
		}
        
		[System.ComponentModel.Description("This Event is fired when the text is changed (duh!)."), 
		System.ComponentModel.Category("Lame Stuff")]
		public event System.EventHandler TextChangedEvent;
        
		protected override void CreateSink() 
		{
			try 
			{
				this.eventMulticaster = new AxLameColorControlEventMulticaster(this);
				this.cookie = new System.Windows.Forms.AxHost.ConnectionPointCookie(this.ocx, this.eventMulticaster, typeof(SimpleVb6AxCtrl.__LameColorControl));
			}
			catch (System.Exception ) 
			{
			}
		}
        
		protected override void DetachSink() 
		{
			try 
			{
				this.cookie.Disconnect();
			}
			catch (System.Exception ) 
			{
			}
		}
        
		protected override void AttachInterfaces() 
		{
			try 
			{
				this.ocx = ((SimpleVb6AxCtrl._LameColorControl)(this.GetOcx()));
			}
			catch (System.Exception ) 
			{
			}
		}
        
		internal void RaiseOnTextChangedEvent(object sender, System.EventArgs e) 
		{
			if ((this.TextChangedEvent != null)) 
			{
				this.TextChangedEvent(sender, e);
			}
		}
	}
    
	public class AxLameColorControlEventMulticaster : SimpleVb6AxCtrl.__LameColorControl 
	{
        
		private AxLameColorControl parent;
        
		public AxLameColorControlEventMulticaster(AxLameColorControl parent) 
		{
			this.parent = parent;
		}
        
		public virtual void TextChanged() 
		{
			System.EventArgs textchangedEvent = new System.EventArgs();
			this.parent.RaiseOnTextChangedEvent(this.parent, textchangedEvent);
		}
	}
}
